# Generated by Django 4.0.3 on 2022-03-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
