# Generated by Django 4.0.2 on 2022-02-20 05:21

from django.db import migrations, models
import face.models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='product_im',
            field=models.ImageField(blank=True, null=True, upload_to=face.models.get_image_path),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='user_im',
            field=models.ImageField(blank=True, null=True, upload_to=face.models.get_image_path),
        ),
    ]
