# Generated by Django 4.0.3 on 2022-03-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deleted_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
